//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSMaps.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSMaps.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageCancel16 {
            get {
                object obj = ResourceManager.GetObject("ImageCancel16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageCancel32 {
            get {
                object obj = ResourceManager.GetObject("ImageCancel32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageClose16 {
            get {
                object obj = ResourceManager.GetObject("ImageClose16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageClose32 {
            get {
                object obj = ResourceManager.GetObject("ImageClose32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageEntidad16 {
            get {
                object obj = ResourceManager.GetObject("ImageEntidad16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageEntidad32 {
            get {
                object obj = ResourceManager.GetObject("ImageEntidad32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageEstablecimiento32 {
            get {
                object obj = ResourceManager.GetObject("ImageEstablecimiento32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageImport32 {
            get {
                object obj = ResourceManager.GetObject("ImageImport32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageItemAdd32 {
            get {
                object obj = ResourceManager.GetObject("ImageItemAdd32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageItemCopy32 {
            get {
                object obj = ResourceManager.GetObject("ImageItemCopy32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageItemDelete32 {
            get {
                object obj = ResourceManager.GetObject("ImageItemDelete32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageItemEdit32 {
            get {
                object obj = ResourceManager.GetObject("ImageItemEdit32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageItemSelect32 {
            get {
                object obj = ResourceManager.GetObject("ImageItemSelect32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageItemView32 {
            get {
                object obj = ResourceManager.GetObject("ImageItemView32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageOk16 {
            get {
                object obj = ResourceManager.GetObject("ImageOk16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageOk32 {
            get {
                object obj = ResourceManager.GetObject("ImageOk32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImagePunto32 {
            get {
                object obj = ResourceManager.GetObject("ImagePunto32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageTablas32 {
            get {
                object obj = ResourceManager.GetObject("ImageTablas32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageWindowCloseAll {
            get {
                object obj = ResourceManager.GetObject("ImageWindowCloseAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al acceder a la base de datos..
        /// </summary>
        internal static string StringDatabaseError {
            get {
                return ResourceManager.GetString("StringDatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se muestran {1} {0}..
        /// </summary>
        internal static string StringDatabaseItemsCountMany {
            get {
                return ResourceManager.GetString("StringDatabaseItemsCountMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay {0} para mostrar..
        /// </summary>
        internal static string StringDatabaseItemsCountNone {
            get {
                return ResourceManager.GetString("StringDatabaseItemsCountNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se muestra 1 {0}..
        /// </summary>
        internal static string StringDatabaseItemsCountOne {
            get {
                return ResourceManager.GetString("StringDatabaseItemsCountOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo desencriptar la contraseña de la conexión a la base de datos.\n\n{0}.
        /// </summary>
        internal static string StringDatabasePasswordUnencryptionError {
            get {
                return ResourceManager.GetString("StringDatabasePasswordUnencryptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al leer los datos desde la base..
        /// </summary>
        internal static string StringDatabaseReadError {
            get {
                return ResourceManager.GetString("StringDatabaseReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al guardar los cambios en la base de datos..
        /// </summary>
        internal static string StringDatabaseSaveError {
            get {
                return ResourceManager.GetString("StringDatabaseSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to que comienzan con:.
        /// </summary>
        internal static string StringTextFilterTypeBegin {
            get {
                return ResourceManager.GetString("StringTextFilterTypeBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to que contienen:.
        /// </summary>
        internal static string StringTextFilterTypeContains {
            get {
                return ResourceManager.GetString("StringTextFilterTypeContains", resourceCulture);
            }
        }
    }
}
