//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSMaps.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSMaps.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al acceder a la base de datos..
        /// </summary>
        internal static string StringDatabaseError {
            get {
                return ResourceManager.GetString("StringDatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al guardar los cambios en la base de datos..
        /// </summary>
        internal static string StringDatabaseSaveError {
            get {
                return ResourceManager.GetString("StringDatabaseSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo especificado no existe..
        /// </summary>
        internal static string StringFileNotFound {
            get {
                return ResourceManager.GetString("StringFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe especificar el archivo que desea importar..
        /// </summary>
        internal static string StringImportFileNotSpecified {
            get {
                return ResourceManager.GetString("StringImportFileNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se han importado {0} puntos..
        /// </summary>
        internal static string StringImportFileSuccesful {
            get {
                return ResourceManager.GetString("StringImportFileSuccesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El contenido del archivo .kml no tiene el formato esperado..
        /// </summary>
        internal static string StringKmlFileInvalidContent {
            get {
                return ResourceManager.GetString("StringKmlFileInvalidContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El contenido del archivo .kml no tiene el formato esperado en las etiquetas &apos;Placemark&apos;..
        /// </summary>
        internal static string StringKmlFileInvalidContentPlacemark {
            get {
                return ResourceManager.GetString("StringKmlFileInvalidContentPlacemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al leer el archivo .kml.
        /// </summary>
        internal static string StringKmlFileReadError {
            get {
                return ResourceManager.GetString("StringKmlFileReadError", resourceCulture);
            }
        }
    }
}
