//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSMaps.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSMaps.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconApplication {
            get {
                object obj = ResourceManager.GetObject("IconApplication", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageCancel16 {
            get {
                object obj = ResourceManager.GetObject("ImageCancel16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageCancel32 {
            get {
                object obj = ResourceManager.GetObject("ImageCancel32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageCardonerSistemas {
            get {
                object obj = ResourceManager.GetObject("ImageCardonerSistemas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageClose16 {
            get {
                object obj = ResourceManager.GetObject("ImageClose16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageClose32 {
            get {
                object obj = ResourceManager.GetObject("ImageClose32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageEntidad32 {
            get {
                object obj = ResourceManager.GetObject("ImageEntidad32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageEstablecimiento32 {
            get {
                object obj = ResourceManager.GetObject("ImageEstablecimiento32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageExport32 {
            get {
                object obj = ResourceManager.GetObject("ImageExport32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageHombre16 {
            get {
                object obj = ResourceManager.GetObject("ImageHombre16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageImport32 {
            get {
                object obj = ResourceManager.GetObject("ImageImport32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageItemAdd32 {
            get {
                object obj = ResourceManager.GetObject("ImageItemAdd32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageItemCopy32 {
            get {
                object obj = ResourceManager.GetObject("ImageItemCopy32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageItemDelete32 {
            get {
                object obj = ResourceManager.GetObject("ImageItemDelete32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageItemEdit32 {
            get {
                object obj = ResourceManager.GetObject("ImageItemEdit32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageItemSelect32 {
            get {
                object obj = ResourceManager.GetObject("ImageItemSelect32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageItemView32 {
            get {
                object obj = ResourceManager.GetObject("ImageItemView32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageLogin48 {
            get {
                object obj = ResourceManager.GetObject("ImageLogin48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageMujer16 {
            get {
                object obj = ResourceManager.GetObject("ImageMujer16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageOk16 {
            get {
                object obj = ResourceManager.GetObject("ImageOk16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageOk32 {
            get {
                object obj = ResourceManager.GetObject("ImageOk32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImagePunto32 {
            get {
                object obj = ResourceManager.GetObject("ImagePunto32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageSearch16 {
            get {
                object obj = ResourceManager.GetObject("ImageSearch16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageSearch32 {
            get {
                object obj = ResourceManager.GetObject("ImageSearch32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageSplash {
            get {
                object obj = ResourceManager.GetObject("ImageSplash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageTablas32 {
            get {
                object obj = ResourceManager.GetObject("ImageTablas32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageWindowCloseAll {
            get {
                object obj = ResourceManager.GetObject("ImageWindowCloseAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to agregar.
        /// </summary>
        internal static string StringActionAdd {
            get {
                return ResourceManager.GetString("StringActionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to borrar.
        /// </summary>
        internal static string StringActionDelete {
            get {
                return ResourceManager.GetString("StringActionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se borrará la {0} seleccionada.
        ///
        ///{1}
        ///
        ///¿Confirma el borrado definitivo?.
        /// </summary>
        internal static string StringActionDeleteConfirmationFemale {
            get {
                return ResourceManager.GetString("StringActionDeleteConfirmationFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se borrará el {0} seleccionado.
        ///
        ///{1}
        ///
        ///¿Confirma el borrado definitivo?.
        /// </summary>
        internal static string StringActionDeleteConfirmationMale {
            get {
                return ResourceManager.GetString("StringActionDeleteConfirmationMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to editar.
        /// </summary>
        internal static string StringActionEdit {
            get {
                return ResourceManager.GetString("StringActionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay ninguna {0} para {1}..
        /// </summary>
        internal static string StringActionNoneFemale {
            get {
                return ResourceManager.GetString("StringActionNoneFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay ningún {0} para {1}..
        /// </summary>
        internal static string StringActionNoneMale {
            get {
                return ResourceManager.GetString("StringActionNoneMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seleccionar.
        /// </summary>
        internal static string StringActionSelect {
            get {
                return ResourceManager.GetString("StringActionSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ver.
        /// </summary>
        internal static string StringActionView {
            get {
                return ResourceManager.GetString("StringActionView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al acceder a la base de datos..
        /// </summary>
        internal static string StringDatabaseError {
            get {
                return ResourceManager.GetString("StringDatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se muestran {1} {0}..
        /// </summary>
        internal static string StringDatabaseItemsCountMany {
            get {
                return ResourceManager.GetString("StringDatabaseItemsCountMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay {0} para mostrar..
        /// </summary>
        internal static string StringDatabaseItemsCountNone {
            get {
                return ResourceManager.GetString("StringDatabaseItemsCountNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se muestra 1 {0}..
        /// </summary>
        internal static string StringDatabaseItemsCountOne {
            get {
                return ResourceManager.GetString("StringDatabaseItemsCountOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo desencriptar la contraseña de la conexión a la base de datos.\n\n{0}.
        /// </summary>
        internal static string StringDatabasePasswordUnencryptionError {
            get {
                return ResourceManager.GetString("StringDatabasePasswordUnencryptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al leer los datos desde la base..
        /// </summary>
        internal static string StringDatabaseReadError {
            get {
                return ResourceManager.GetString("StringDatabaseReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al guardar los cambios en la base de datos..
        /// </summary>
        internal static string StringDatabaseSaveError {
            get {
                return ResourceManager.GetString("StringDatabaseSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha realizado cambios en los datos y seleccionó cancelar, los cambios se perderán.
        ///
        ///¿Confirma la pérdida de los cambios?.
        /// </summary>
        internal static string StringEntityCancelChanges {
            get {
                return ResourceManager.GetString("StringEntityCancelChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe especificar la {1} de la {0}..
        /// </summary>
        internal static string StringEntityDataVerificationFemaleFieldRequiredFemale {
            get {
                return ResourceManager.GetString("StringEntityDataVerificationFemaleFieldRequiredFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe especificar la {1} del {0}..
        /// </summary>
        internal static string StringEntityDataVerificationFemaleFieldRequiredMale {
            get {
                return ResourceManager.GetString("StringEntityDataVerificationFemaleFieldRequiredMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe especificar el {1} de la {0}..
        /// </summary>
        internal static string StringEntityDataVerificationMaleFieldRequiredFemale {
            get {
                return ResourceManager.GetString("StringEntityDataVerificationMaleFieldRequiredFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe especificar el {1} del {0}..
        /// </summary>
        internal static string StringEntityDataVerificationMaleFieldRequiredMale {
            get {
                return ResourceManager.GetString("StringEntityDataVerificationMaleFieldRequiredMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede {1} la {0} porque ya existe una con el mismo id..
        /// </summary>
        internal static string StringEntityDuplicatedPrimaryKeyErrorFemale {
            get {
                return ResourceManager.GetString("StringEntityDuplicatedPrimaryKeyErrorFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede {1} el {0} porque ya existe uno con el mismo id..
        /// </summary>
        internal static string StringEntityDuplicatedPrimaryKeyErrorMale {
            get {
                return ResourceManager.GetString("StringEntityDuplicatedPrimaryKeyErrorMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede {1} la {0} porque ya existe una con datos iguales..
        /// </summary>
        internal static string StringEntityDuplicatedUniqueKeyErrorFemale {
            get {
                return ResourceManager.GetString("StringEntityDuplicatedUniqueKeyErrorFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede {1} el {0} porque ya existe uno con datos iguales..
        /// </summary>
        internal static string StringEntityDuplicatedUniqueKeyErrorMale {
            get {
                return ResourceManager.GetString("StringEntityDuplicatedUniqueKeyErrorMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener la valores iniciales para la nueva {0}..
        /// </summary>
        internal static string StringEntityNewValuesErrorFemale {
            get {
                return ResourceManager.GetString("StringEntityNewValuesErrorFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener la valores iniciales para el nuevo {0}..
        /// </summary>
        internal static string StringEntityNewValuesErrorMale {
            get {
                return ResourceManager.GetString("StringEntityNewValuesErrorMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede {1} la {0} porque tiene datos relacionados..
        /// </summary>
        internal static string StringEntityRelatedDataErrorFemale {
            get {
                return ResourceManager.GetString("StringEntityRelatedDataErrorFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede {1} el {0} porque tiene datos relacionados..
        /// </summary>
        internal static string StringEntityRelatedDataErrorMale {
            get {
                return ResourceManager.GetString("StringEntityRelatedDataErrorMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al actualizar los cambios de la {0} en la base de datos..
        /// </summary>
        internal static string StringEntitySaveChangesErrorFemale {
            get {
                return ResourceManager.GetString("StringEntitySaveChangesErrorFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al actualizar los cambios de el {0} en la base de datos..
        /// </summary>
        internal static string StringEntitySaveChangesErrorMale {
            get {
                return ResourceManager.GetString("StringEntitySaveChangesErrorMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe especificar el archivo de destino al que desea exportar..
        /// </summary>
        internal static string StringExportFileNotSpecified {
            get {
                return ResourceManager.GetString("StringExportFileNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo especificado no existe..
        /// </summary>
        internal static string StringFileNotFound {
            get {
                return ResourceManager.GetString("StringFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Femenino.
        /// </summary>
        internal static string StringGenderFemale {
            get {
                return ResourceManager.GetString("StringGenderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masculino.
        /// </summary>
        internal static string StringGenderMale {
            get {
                return ResourceManager.GetString("StringGenderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos de intercambio de GPS (*.gpx)|*.gpx|Todos los archivos (*.*)|*.*.
        /// </summary>
        internal static string StringGpsFileSaveDialogFilter {
            get {
                return ResourceManager.GetString("StringGpsFileSaveDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especifique el archivo de GPS.
        /// </summary>
        internal static string StringGpsFileSaveDialogTitle {
            get {
                return ResourceManager.GetString("StringGpsFileSaveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe especificar el archivo que desea importar..
        /// </summary>
        internal static string StringImportFileNotSpecified {
            get {
                return ResourceManager.GetString("StringImportFileNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se han importado {0} puntos..
        /// </summary>
        internal static string StringImportFileSuccesful {
            get {
                return ResourceManager.GetString("StringImportFileSuccesful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El contenido del archivo no es el esperado..
        /// </summary>
        internal static string StringImportUnknownFileInvalidContent {
            get {
                return ResourceManager.GetString("StringImportUnknownFileInvalidContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al leer el archivo para detectar el formato..
        /// </summary>
        internal static string StringImportUnknownFileReadError {
            get {
                return ResourceManager.GetString("StringImportUnknownFileReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas.
        /// </summary>
        internal static string StringItemAllFemale {
            get {
                return ResourceManager.GetString("StringItemAllFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        internal static string StringItemAllMale {
            get {
                return ResourceManager.GetString("StringItemAllMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completa.
        /// </summary>
        internal static string StringItemCompleteFemale {
            get {
                return ResourceManager.GetString("StringItemCompleteFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completo.
        /// </summary>
        internal static string StringItemCompleteMale {
            get {
                return ResourceManager.GetString("StringItemCompleteMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacía.
        /// </summary>
        internal static string StringItemEmptyFemale {
            get {
                return ResourceManager.GetString("StringItemEmptyFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacío.
        /// </summary>
        internal static string StringItemEmptyMale {
            get {
                return ResourceManager.GetString("StringItemEmptyMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ».
        /// </summary>
        internal static string StringItemEndChar {
            get {
                return ResourceManager.GetString("StringItemEndChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No especifica.
        /// </summary>
        internal static string StringItemNotSpecified {
            get {
                return ResourceManager.GetString("StringItemNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «.
        /// </summary>
        internal static string StringItemStartChar {
            get {
                return ResourceManager.GetString("StringItemStartChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El contenido del archivo .kml no tiene el formato esperado..
        /// </summary>
        internal static string StringKmlFileInvalidContent {
            get {
                return ResourceManager.GetString("StringKmlFileInvalidContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El contenido del archivo .kml no tiene el formato esperado en las etiquetas &apos;Placemark&apos;..
        /// </summary>
        internal static string StringKmlFileInvalidContentPlacemark {
            get {
                return ResourceManager.GetString("StringKmlFileInvalidContentPlacemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos de Google Earth (*.kmz, *.kml)|*.kmz;*.kml|Todos los archivos (*.*)|*.*.
        /// </summary>
        internal static string StringKmlFileOpenDialogFilter {
            get {
                return ResourceManager.GetString("StringKmlFileOpenDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el archivo de Google Earth.
        /// </summary>
        internal static string StringKmlFileOpenDialogTitle {
            get {
                return ResourceManager.GetString("StringKmlFileOpenDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al leer el archivo .kml.
        /// </summary>
        internal static string StringKmlFileReadError {
            get {
                return ResourceManager.GetString("StringKmlFileReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva.
        /// </summary>
        internal static string StringNewFemale {
            get {
                return ResourceManager.GetString("StringNewFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        internal static string StringNewMale {
            get {
                return ResourceManager.GetString("StringNewMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string StringNo {
            get {
                return ResourceManager.GetString("StringNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tiene autorización para realizar esta acción..
        /// </summary>
        internal static string StringNotPermission {
            get {
                return ResourceManager.GetString("StringNotPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se deben especificar al menos {0} letras para buscar..
        /// </summary>
        internal static string StringTextFilterMinimumLenght {
            get {
                return ResourceManager.GetString("StringTextFilterMinimumLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to que comienzan con:.
        /// </summary>
        internal static string StringTextFilterTypeBegin {
            get {
                return ResourceManager.GetString("StringTextFilterTypeBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to que contienen:.
        /// </summary>
        internal static string StringTextFilterTypeContains {
            get {
                return ResourceManager.GetString("StringTextFilterTypeContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sí.
        /// </summary>
        internal static string StringYes {
            get {
                return ResourceManager.GetString("StringYes", resourceCulture);
            }
        }
    }
}
