// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CSMaps.Models;

public partial class CSMapsContext : DbContext
{
    public CSMapsContext(DbContextOptions<CSMapsContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Entidad> Entidad { get; set; }

    public virtual DbSet<Establecimiento> Establecimiento { get; set; }

    public virtual DbSet<EventoTipo> EventoTipo { get; set; }

    public virtual DbSet<Grupo> Grupo { get; set; }

    public virtual DbSet<GrupoPunto> GrupoPunto { get; set; }

    public virtual DbSet<Parametro> Parametro { get; set; }

    public virtual DbSet<ParametroTipo> ParametroTipo { get; set; }

    public virtual DbSet<Permiso> Permiso { get; set; }

    public virtual DbSet<PermisoGrupo> PermisoGrupo { get; set; }

    public virtual DbSet<PermisoTipo> PermisoTipo { get; set; }

    public virtual DbSet<Punto> Punto { get; set; }

    public virtual DbSet<PuntoDato> PuntoDato { get; set; }

    public virtual DbSet<PuntoEvento> PuntoEvento { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

    public virtual DbSet<UsuarioGrupo> UsuarioGrupo { get; set; }

    public virtual DbSet<UsuarioGrupoPermiso> UsuarioGrupoPermiso { get; set; }

    public virtual DbSet<UsuarioParametro> UsuarioParametro { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Entidad>(entity =>
        {
            entity.HasKey(e => e.IdEntidad);

            entity.HasIndex(e => e.Nombre, "UI_Entidad_Nombre").IsUnique();

            entity.Property(e => e.IdEntidad).ValueGeneratedNever();
            entity.Property(e => e.FechaHoraCreacion)
                .HasDefaultValueSql("(getdate())", "DF_Entidad_FechaHoraCreacion")
                .HasColumnType("smalldatetime");
            entity.Property(e => e.FechaHoraUltimaModificacion)
                .HasDefaultValueSql("(getdate())", "DF_Entidad_UltimaActualizacion")
                .HasColumnType("smalldatetime");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.TelefonoMovil)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.IdUsuarioCreacionNavigation).WithMany(p => p.EntidadIdUsuarioCreacionNavigation)
                .HasForeignKey(d => d.IdUsuarioCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Entidad_UsuarioCreacion");

            entity.HasOne(d => d.IdUsuarioUltimaModificacionNavigation).WithMany(p => p.EntidadIdUsuarioUltimaModificacionNavigation)
                .HasForeignKey(d => d.IdUsuarioUltimaModificacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Entidad_UsuarioUltimaModificacion");
        });

        modelBuilder.Entity<Establecimiento>(entity =>
        {
            entity.HasKey(e => e.IdEstablecimiento);

            entity.Property(e => e.IdEstablecimiento).ValueGeneratedNever();
            entity.Property(e => e.FechaHoraCreacion)
                .HasDefaultValueSql("(getdate())", "DF_Establecimiento_FechaHoraCreacion")
                .HasColumnType("smalldatetime");
            entity.Property(e => e.FechaHoraUltimaModificacion)
                .HasDefaultValueSql("(getdate())", "DF_Establecimiento_UltimaActualizacion")
                .HasColumnType("smalldatetime");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TelefonoMovil)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.IdEntidadNavigation).WithMany(p => p.Establecimiento)
                .HasForeignKey(d => d.IdEntidad)
                .HasConstraintName("FK_Establecimiento_Entidad");

            entity.HasOne(d => d.IdUsuarioCreacionNavigation).WithMany(p => p.EstablecimientoIdUsuarioCreacionNavigation)
                .HasForeignKey(d => d.IdUsuarioCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Establecimiento_UsuarioCreacion");

            entity.HasOne(d => d.IdUsuarioUltimaModificacionNavigation).WithMany(p => p.EstablecimientoIdUsuarioUltimaModificacionNavigation)
                .HasForeignKey(d => d.IdUsuarioUltimaModificacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Establecimiento_UsuarioUltimaModificacion");
        });

        modelBuilder.Entity<EventoTipo>(entity =>
        {
            entity.HasKey(e => e.IdEventoTipo);

            entity.HasIndex(e => e.Nombre, "UI_EventoTipo_Nombre").IsUnique();

            entity.Property(e => e.EsActivo).HasDefaultValue(true, "DF_EventoTipo_Activo");
            entity.Property(e => e.FechaHoraCreacion)
                .HasDefaultValueSql("(getdate())", "DF_EventoTipo_FechaHoraCreacion")
                .HasColumnType("smalldatetime");
            entity.Property(e => e.FechaHoraUltimaModificacion)
                .HasDefaultValueSql("(getdate())", "DF_EventoTipo_UltimaActualizacion")
                .HasColumnType("smalldatetime");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.IdUsuarioCreacionNavigation).WithMany(p => p.EventoTipoIdUsuarioCreacionNavigation)
                .HasForeignKey(d => d.IdUsuarioCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EventoTipo_UsuarioCreacion");

            entity.HasOne(d => d.IdUsuarioUltimaModificacionNavigation).WithMany(p => p.EventoTipoIdUsuarioUltimaModificacionNavigation)
                .HasForeignKey(d => d.IdUsuarioUltimaModificacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EventoTipo_UsuarioUltimaModificacion");
        });

        modelBuilder.Entity<Grupo>(entity =>
        {
            entity.HasKey(e => e.IdGrupo);

            entity.HasIndex(e => e.Nombre, "UI_Grupo_Nombre").IsUnique();

            entity.Property(e => e.IdGrupo).ValueGeneratedNever();
            entity.Property(e => e.EsActivo).HasDefaultValue(true, "DF_Grupo_Activo");
            entity.Property(e => e.FechaHoraCreacion)
                .HasDefaultValueSql("(getdate())", "DF_Grupo_FechaHoraCreacion")
                .HasColumnType("smalldatetime");
            entity.Property(e => e.FechaHoraUltimaModificacion)
                .HasDefaultValueSql("(getdate())", "DF_Grupo_UltimaActualizacion")
                .HasColumnType("smalldatetime");
            entity.Property(e => e.IconoMapaColor)
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.IconoMapaDireccion)
                .HasMaxLength(75)
                .IsUnicode(false);
            entity.Property(e => e.IconoMapaHotSpotXUnits)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.IconoMapaHotSpotYUnits)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.IconoMapaLeyendaTexto)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.IdUsuarioCreacionNavigation).WithMany(p => p.GrupoIdUsuarioCreacionNavigation)
                .HasForeignKey(d => d.IdUsuarioCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Grupo_UsuarioCreacion");

            entity.HasOne(d => d.IdUsuarioUltimaModificacionNavigation).WithMany(p => p.GrupoIdUsuarioUltimaModificacionNavigation)
                .HasForeignKey(d => d.IdUsuarioUltimaModificacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Grupo_UsuarioUltimaModificacion");
        });

        modelBuilder.Entity<GrupoPunto>(entity =>
        {
            entity.HasKey(e => new { e.IdGrupo, e.IdPunto });

            entity.Property(e => e.FechaHoraCreacion)
                .HasDefaultValueSql("(getdate())", "DF_GrupoPunto_UltimaActualizacion")
                .HasColumnType("smalldatetime");

            entity.HasOne(d => d.IdGrupoNavigation).WithMany(p => p.GrupoPunto)
                .HasForeignKey(d => d.IdGrupo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GrupoPunto_Grupo");

            entity.HasOne(d => d.IdPuntoNavigation).WithMany(p => p.GrupoPunto)
                .HasForeignKey(d => d.IdPunto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GrupoPunto_Punto");

            entity.HasOne(d => d.IdUsuarioCreacionNavigation).WithMany(p => p.GrupoPunto)
                .HasForeignKey(d => d.IdUsuarioCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GrupoPunto_UsuarioCreacion");
        });

        modelBuilder.Entity<Parametro>(entity =>
        {
            entity.HasKey(e => e.IdParametro);

            entity.Property(e => e.IdParametro).ValueGeneratedNever();
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.FechaHora).HasColumnType("smalldatetime");
            entity.Property(e => e.Imagen).HasColumnType("image");
            entity.Property(e => e.Moneda).HasColumnType("money");
            entity.Property(e => e.Notas).IsUnicode(false);
            entity.Property(e => e.NumeroDecimal).HasColumnType("decimal(18, 9)");
            entity.Property(e => e.Texto).IsUnicode(false);

            entity.HasOne(d => d.IdParametroTipoNavigation).WithMany(p => p.Parametro)
                .HasForeignKey(d => d.IdParametroTipo)
                .HasConstraintName("FK_Parametro_ParametroTipo");
        });

        modelBuilder.Entity<ParametroTipo>(entity =>
        {
            entity.HasKey(e => e.IdParametroTipo);

            entity.HasIndex(e => e.Nombre, "UI_ParametroTipo_Nombre").IsUnique();

            entity.Property(e => e.Descripcion)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Permiso>(entity =>
        {
            entity.HasKey(e => e.IdPermiso);

            entity.HasIndex(e => new { e.IdPermisoGrupo, e.IdPermisoTipo }, "UI_Permiso_Grupo_Tipo").IsUnique();

            entity.Property(e => e.IdPermiso).ValueGeneratedNever();

            entity.HasOne(d => d.IdPermisoGrupoNavigation).WithMany(p => p.Permiso)
                .HasForeignKey(d => d.IdPermisoGrupo)
                .HasConstraintName("FK_Permiso_PermisoGrupo");

            entity.HasOne(d => d.IdPermisoTipoNavigation).WithMany(p => p.Permiso)
                .HasForeignKey(d => d.IdPermisoTipo)
                .HasConstraintName("FK_Permiso_PermisoTipo");
        });

        modelBuilder.Entity<PermisoGrupo>(entity =>
        {
            entity.HasKey(e => e.IdPermisoGrupo);

            entity.HasIndex(e => e.Nombre, "UI_PermisoGrupo_Nombre");

            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<PermisoTipo>(entity =>
        {
            entity.HasKey(e => e.IdPermisoTipo);

            entity.HasIndex(e => e.Nombre, "UI_PermisoTipo_Nombre");

            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Punto>(entity =>
        {
            entity.HasKey(e => e.IdPunto);

            entity.HasIndex(e => e.Nombre, "UI_Punto_Nombre").IsUnique();

            entity.Property(e => e.IdPunto).ValueGeneratedNever();
            entity.Property(e => e.Altitud).HasColumnType("decimal(6, 2)");
            entity.Property(e => e.FechaHoraCreacion)
                .HasDefaultValueSql("(getdate())", "DF_Punto_FechaHoraCreacion")
                .HasColumnType("smalldatetime");
            entity.Property(e => e.FechaHoraUltimaModificacion)
                .HasDefaultValueSql("(getdate())", "DF_Punto_UltimaActualizacion")
                .HasColumnType("smalldatetime");
            entity.Property(e => e.Latitud).HasColumnType("decimal(8, 6)");
            entity.Property(e => e.Longitud).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.IdUsuarioCreacionNavigation).WithMany(p => p.PuntoIdUsuarioCreacionNavigation)
                .HasForeignKey(d => d.IdUsuarioCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Punto_UsuarioCreacion");

            entity.HasOne(d => d.IdUsuarioUltimaModificacionNavigation).WithMany(p => p.PuntoIdUsuarioUltimaModificacionNavigation)
                .HasForeignKey(d => d.IdUsuarioUltimaModificacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Punto_UsuarioUltimaModificacion");
        });

        modelBuilder.Entity<PuntoDato>(entity =>
        {
            entity.HasKey(e => e.IdPunto);

            entity.HasIndex(e => e.ChapaNumero, "UI_PuntoDato_ChapaNumero")
                .IsUnique()
                .HasFilter("([ChapaNumero] IS NOT NULL)");

            entity.Property(e => e.IdPunto).ValueGeneratedNever();
            entity.Property(e => e.FechaHoraCreacion)
                .HasDefaultValueSql("(getdate())", "DF_PuntoDato_FechaHoraCreacion")
                .HasColumnType("smalldatetime");
            entity.Property(e => e.FechaHoraUltimaModificacion)
                .HasDefaultValueSql("(getdate())", "DF_PuntoDato_UltimaActualizacion")
                .HasColumnType("smalldatetime");
            entity.Property(e => e.Notas).IsUnicode(false);

            entity.HasOne(d => d.IdEstablecimientoNavigation).WithMany(p => p.PuntoDato)
                .HasForeignKey(d => d.IdEstablecimiento)
                .HasConstraintName("FK_PuntoDato_Establecimiento");

            entity.HasOne(d => d.IdPuntoNavigation).WithOne(p => p.PuntoDato)
                .HasForeignKey<PuntoDato>(d => d.IdPunto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PuntoDato_Punto");

            entity.HasOne(d => d.IdUsuarioCreacionNavigation).WithMany(p => p.PuntoDatoIdUsuarioCreacionNavigation)
                .HasForeignKey(d => d.IdUsuarioCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PuntoDato_UsuarioCreacion");

            entity.HasOne(d => d.IdUsuarioUltimaModificacionNavigation).WithMany(p => p.PuntoDatoIdUsuarioUltimaModificacionNavigation)
                .HasForeignKey(d => d.IdUsuarioUltimaModificacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PuntoDato_UsuarioUltimaModificacion");
        });

        modelBuilder.Entity<PuntoEvento>(entity =>
        {
            entity.HasKey(e => new { e.IdPunto, e.IdEvento });

            entity.Property(e => e.FechaHora).HasColumnType("smalldatetime");
            entity.Property(e => e.FechaHoraCreacion)
                .HasDefaultValueSql("(getdate())", "DF_PuntoEvento_FechaHoraCreacion")
                .HasColumnType("smalldatetime");
            entity.Property(e => e.FechaHoraUltimaModificacion)
                .HasDefaultValueSql("(getdate())", "DF_PuntoEvento_UltimaActualizacion")
                .HasColumnType("smalldatetime");
            entity.Property(e => e.Notas).IsUnicode(false);

            entity.HasOne(d => d.IdEventoTipoNavigation).WithMany(p => p.PuntoEvento)
                .HasForeignKey(d => d.IdEventoTipo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PuntoEvento_EventoTipo");

            entity.HasOne(d => d.IdPuntoNavigation).WithMany(p => p.PuntoEvento)
                .HasForeignKey(d => d.IdPunto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PuntoEvento_Punto");

            entity.HasOne(d => d.IdUsuarioCreacionNavigation).WithMany(p => p.PuntoEventoIdUsuarioCreacionNavigation)
                .HasForeignKey(d => d.IdUsuarioCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PuntoEvento_UsuarioCreacion");

            entity.HasOne(d => d.IdUsuarioUltimaModificacionNavigation).WithMany(p => p.PuntoEventoIdUsuarioUltimaModificacionNavigation)
                .HasForeignKey(d => d.IdUsuarioUltimaModificacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PuntoEvento_UsuarioUltimaModificacion");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.IdUsuario);

            entity.HasIndex(e => e.Descripcion, "UI_Usuario_Descripcion").IsUnique();

            entity.HasIndex(e => e.Nombre, "UI_Usuario_Nombre").IsUnique();

            entity.Property(e => e.IdUsuario).ValueGeneratedNever();
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FechaHoraCreacion).HasColumnType("smalldatetime");
            entity.Property(e => e.FechaHoraUltimaModificacion).HasColumnType("smalldatetime");
            entity.Property(e => e.Genero)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Notas).IsUnicode(false);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(128)
                .IsUnicode(false);

            entity.HasOne(d => d.IdUsuarioCreacionNavigation).WithMany(p => p.InverseIdUsuarioCreacionNavigation)
                .HasForeignKey(d => d.IdUsuarioCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Usuario_Usuario_Creacion");

            entity.HasOne(d => d.IdUsuarioGrupoNavigation).WithMany(p => p.Usuario)
                .HasForeignKey(d => d.IdUsuarioGrupo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Usuario_UsuarioGrupo");

            entity.HasOne(d => d.IdUsuarioUltimaModificacionNavigation).WithMany(p => p.InverseIdUsuarioUltimaModificacionNavigation)
                .HasForeignKey(d => d.IdUsuarioUltimaModificacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Usuario_Usuario_UltimaModificacion");
        });

        modelBuilder.Entity<UsuarioGrupo>(entity =>
        {
            entity.HasKey(e => e.IdUsuarioGrupo);

            entity.HasIndex(e => e.Nombre, "UI_UsuarioGrupo_Nombre").IsUnique();

            entity.Property(e => e.FechaHoraCreacion).HasColumnType("smalldatetime");
            entity.Property(e => e.FechaHoraUltimaModificacion).HasColumnType("smalldatetime");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Notas).IsUnicode(false);

            entity.HasOne(d => d.IdUsuarioCreacionNavigation).WithMany(p => p.UsuarioGrupoIdUsuarioCreacionNavigation)
                .HasForeignKey(d => d.IdUsuarioCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsuarioGrupo_Usuario_Creacion");

            entity.HasOne(d => d.IdUsuarioUltimaModificacionNavigation).WithMany(p => p.UsuarioGrupoIdUsuarioUltimaModificacionNavigation)
                .HasForeignKey(d => d.IdUsuarioUltimaModificacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsuarioGrupo_Usuario_UltimaModificacion");
        });

        modelBuilder.Entity<UsuarioGrupoPermiso>(entity =>
        {
            entity.HasKey(e => new { e.IdUsuarioGrupo, e.IdPermiso });

            entity.HasOne(d => d.IdPermisoNavigation).WithMany(p => p.UsuarioGrupoPermiso)
                .HasForeignKey(d => d.IdPermiso)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsuarioGrupoPermiso_Permiso");

            entity.HasOne(d => d.IdUsuarioCreacionNavigation).WithMany(p => p.UsuarioGrupoPermiso)
                .HasForeignKey(d => d.IdUsuarioCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsuarioGrupoPermiso_Usuario");

            entity.HasOne(d => d.IdUsuarioGrupoNavigation).WithMany(p => p.UsuarioGrupoPermiso)
                .HasForeignKey(d => d.IdUsuarioGrupo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsuarioGrupoPermiso_UsuarioGrupo");
        });

        modelBuilder.Entity<UsuarioParametro>(entity =>
        {
            entity.HasKey(e => new { e.IdUsuario, e.IdParametro });

            entity.Property(e => e.FechaHora).HasColumnType("smalldatetime");
            entity.Property(e => e.Imagen).HasColumnType("image");
            entity.Property(e => e.Moneda).HasColumnType("money");
            entity.Property(e => e.Notas).IsUnicode(false);
            entity.Property(e => e.NumeroDecimal).HasColumnType("decimal(18, 9)");
            entity.Property(e => e.Texto).IsUnicode(false);

            entity.HasOne(d => d.IdParametroNavigation).WithMany(p => p.UsuarioParametro)
                .HasForeignKey(d => d.IdParametro)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsuarioParametro_Parametro");

            entity.HasOne(d => d.IdParametroTipoNavigation).WithMany(p => p.UsuarioParametro)
                .HasForeignKey(d => d.IdParametroTipo)
                .HasConstraintName("FK_UsuarioParametro_UsuarioParametro");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.UsuarioParametro)
                .HasForeignKey(d => d.IdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsuarioParametro_Usuario");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}