// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSMaps.Models;

public partial class Entidad
{
    public short IdEntidad { get; set; }

    public string NombreTemp { get; set; }

    public string Nombre { get; set; }

    public string TelefonoMovil { get; set; }

    public DateTime UltimaActualizacion { get; set; }

    public virtual ICollection<Establecimiento> Establecimientos { get; set; } = new List<Establecimiento>();
}