// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSMaps.Models;

public partial class EventoTipo
{
    public byte IdEventoTipo { get; set; }

    public string Nombre { get; set; }

    public bool Activo { get; set; }

    public DateTime UltimaActualizacion { get; set; }

    public virtual ICollection<PuntoEvento> PuntoEventos { get; set; } = new List<PuntoEvento>();
}