// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSMaps.Models;

public partial class Grupo
{
    public short IdGrupo { get; set; }

    public string Nombre { get; set; }

    public string GoogleMapsStyleId { get; set; }

    public byte[] GoogleMapsIcon { get; set; }

    public bool Activo { get; set; }

    public DateTime UltimaActualizacion { get; set; }

    public virtual ICollection<GrupoPunto> GrupoPuntos { get; set; } = new List<GrupoPunto>();
}