// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSMaps.Models;

public partial class GrupoPunto
{
    public short IdGrupo { get; set; }

    public int IdPunto { get; set; }

    public DateTime UltimaActualizacion { get; set; }

    public virtual Grupo IdGrupoNavigation { get; set; }

    public virtual Punto IdPuntoNavigation { get; set; }
}