// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CSMaps.Models
{
    public partial class ObtenerPuntosDatosYEventosResult
    {
        public int IdPunto { get; set; }
        public string PuntoNombre { get; set; }
        [Column("Latitud", TypeName = "decimal(8,6)")]
        public decimal Latitud { get; set; }
        [Column("Longitud", TypeName = "decimal(9,6)")]
        public decimal Longitud { get; set; }
        public int? ChapaNumero { get; set; }
        public short? IdEstablecimiento { get; set; }
        public string EstablecimientoNombre { get; set; }
        public byte? IdEventoTipo { get; set; }
        public string EventoTipoNombre { get; set; }
        public DateTime? FechaHora { get; set; }
    }
}
