// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSMaps.Models;

public partial class Partido
{
    public byte IdPartido { get; set; }

    public string Nombre { get; set; }

    public DateTime UltimaActualizacion { get; set; }
}