// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSMaps.Models;

public partial class PermisoTipo
{
    public byte IdPermisoTipo { get; set; }

    public string Nombre { get; set; }

    public byte? Orden { get; set; }

    public virtual ICollection<Permiso> Permisos { get; set; } = new List<Permiso>();
}