// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSMaps.Models;

public partial class Permiso
{
    public short IdPermiso { get; set; }

    public byte? IdPermisoGrupo { get; set; }

    public byte? IdPermisoTipo { get; set; }

    public byte? Orden { get; set; }

    public virtual PermisoGrupo IdPermisoGrupoNavigation { get; set; }

    public virtual PermisoTipo IdPermisoTipoNavigation { get; set; }

    public virtual ICollection<UsuarioGrupoPermiso> UsuarioGrupoPermisos { get; set; } = new List<UsuarioGrupoPermiso>();
}