// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSMaps.Models;

public partial class PuntoDato
{
    public int IdPunto { get; set; }

    public short? IdEstablecimiento { get; set; }

    public int? ChapaNumero { get; set; }

    public DateTime UltimaActualizacion { get; set; }

    public virtual Establecimiento IdEstablecimientoNavigation { get; set; }

    public virtual Punto IdPuntoNavigation { get; set; }
}