// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSMaps.Models;

public partial class Punto
{
    public int IdPunto { get; set; }

    public string Nombre { get; set; }

    public decimal Latitud { get; set; }

    public decimal Longitud { get; set; }

    public decimal Altitud { get; set; }

    public DateTime UltimaActualizacion { get; set; }

    public virtual ICollection<GrupoPunto> GrupoPuntos { get; set; } = new List<GrupoPunto>();

    public virtual PuntoDato PuntoDato { get; set; }
}