// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSMaps.Models;

public partial class UsuarioParametro
{
    public short IdUsuario { get; set; }

    public short IdParametro { get; set; }

    public byte? IdParametroTipo { get; set; }

    public string Texto { get; set; }

    public int? NumeroEntero { get; set; }

    public decimal? NumeroDecimal { get; set; }

    public decimal? Moneda { get; set; }

    public DateTime? FechaHora { get; set; }

    public bool? SiNo { get; set; }

    public byte[] Imagen { get; set; }

    public string Notas { get; set; }

    public virtual Parametro IdParametroNavigation { get; set; }

    public virtual ParametroTipo IdParametroTipoNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}