// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSMaps.Models;

public partial class UsuarioGrupo
{
    public byte IdUsuarioGrupo { get; set; }

    public string Nombre { get; set; }

    public string Notas { get; set; }

    public bool EsActivo { get; set; }

    public short IdUsuarioCreacion { get; set; }

    public DateTime FechaHoraCreacion { get; set; }

    public short IdUsuarioUltimaModificacion { get; set; }

    public DateTime FechaHoraUltimaModificacion { get; set; }

    public virtual Usuario IdUsuarioCreacionNavigation { get; set; }

    public virtual Usuario IdUsuarioUltimaModificacionNavigation { get; set; }

    public virtual ICollection<UsuarioGrupoPermiso> UsuarioGrupoPermisos { get; set; } = new List<UsuarioGrupoPermiso>();

    public virtual ICollection<Usuario> Usuarios { get; set; } = new List<Usuario>();
}