// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSMaps.Models;

public partial class Usuario
{
    public short IdUsuario { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public string Password { get; set; }

    public string Genero { get; set; }

    public byte IdUsuarioGrupo { get; set; }

    public string Notas { get; set; }

    public bool EsActivo { get; set; }

    public short IdUsuarioCreacion { get; set; }

    public DateTime FechaHoraCreacion { get; set; }

    public short IdUsuarioUltimaModificacion { get; set; }

    public DateTime FechaHoraUltimaModificacion { get; set; }

    public virtual ICollection<Entidad> EntidadIdUsuarioCreacionNavigations { get; set; } = new List<Entidad>();

    public virtual ICollection<Entidad> EntidadIdUsuarioUltimaModificacionNavigations { get; set; } = new List<Entidad>();

    public virtual ICollection<Establecimiento> EstablecimientoIdUsuarioCreacionNavigations { get; set; } = new List<Establecimiento>();

    public virtual ICollection<Establecimiento> EstablecimientoIdUsuarioUltimaModificacionNavigations { get; set; } = new List<Establecimiento>();

    public virtual ICollection<EventoTipo> EventoTipoIdUsuarioCreacionNavigations { get; set; } = new List<EventoTipo>();

    public virtual ICollection<EventoTipo> EventoTipoIdUsuarioUltimaModificacionNavigations { get; set; } = new List<EventoTipo>();

    public virtual ICollection<Grupo> GrupoIdUsuarioCreacionNavigations { get; set; } = new List<Grupo>();

    public virtual ICollection<Grupo> GrupoIdUsuarioUltimaModificacionNavigations { get; set; } = new List<Grupo>();

    public virtual ICollection<GrupoPunto> GrupoPuntos { get; set; } = new List<GrupoPunto>();

    public virtual Usuario IdUsuarioCreacionNavigation { get; set; }

    public virtual UsuarioGrupo IdUsuarioGrupoNavigation { get; set; }

    public virtual Usuario IdUsuarioUltimaModificacionNavigation { get; set; }

    public virtual ICollection<Usuario> InverseIdUsuarioCreacionNavigation { get; set; } = new List<Usuario>();

    public virtual ICollection<Usuario> InverseIdUsuarioUltimaModificacionNavigation { get; set; } = new List<Usuario>();

    public virtual ICollection<PuntoDato> PuntoDatoIdUsuarioCreacionNavigations { get; set; } = new List<PuntoDato>();

    public virtual ICollection<PuntoDato> PuntoDatoIdUsuarioUltimaModificacionNavigations { get; set; } = new List<PuntoDato>();

    public virtual ICollection<PuntoEvento> PuntoEventoIdUsuarioCreacionNavigations { get; set; } = new List<PuntoEvento>();

    public virtual ICollection<PuntoEvento> PuntoEventoIdUsuarioUltimaModificacionNavigations { get; set; } = new List<PuntoEvento>();

    public virtual ICollection<Punto> PuntoIdUsuarioCreacionNavigations { get; set; } = new List<Punto>();

    public virtual ICollection<Punto> PuntoIdUsuarioUltimaModificacionNavigations { get; set; } = new List<Punto>();

    public virtual ICollection<UsuarioGrupo> UsuarioGrupoIdUsuarioCreacionNavigations { get; set; } = new List<UsuarioGrupo>();

    public virtual ICollection<UsuarioGrupo> UsuarioGrupoIdUsuarioUltimaModificacionNavigations { get; set; } = new List<UsuarioGrupo>();

    public virtual ICollection<UsuarioGrupoPermiso> UsuarioGrupoPermisos { get; set; } = new List<UsuarioGrupoPermiso>();

    public virtual ICollection<UsuarioParametro> UsuarioParametros { get; set; } = new List<UsuarioParametro>();
}