// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CSMaps.Models;

public partial class Usuario
{
    public short IdUsuario { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public string Password { get; set; }

    public string Genero { get; set; }

    public byte IdUsuarioGrupo { get; set; }

    public string Notas { get; set; }

    public bool EsActivo { get; set; }

    public short IdUsuarioCreacion { get; set; }

    public DateTime FechaHoraCreacion { get; set; }

    public short IdUsuarioUltimaModificacion { get; set; }

    public DateTime FechaHoraUltimaModificacion { get; set; }

    public virtual ICollection<Entidad> EntidadIdUsuarioCreacionNavigation { get; set; } = new List<Entidad>();

    public virtual ICollection<Entidad> EntidadIdUsuarioUltimaModificacionNavigation { get; set; } = new List<Entidad>();

    public virtual ICollection<Establecimiento> EstablecimientoIdUsuarioCreacionNavigation { get; set; } = new List<Establecimiento>();

    public virtual ICollection<Establecimiento> EstablecimientoIdUsuarioUltimaModificacionNavigation { get; set; } = new List<Establecimiento>();

    public virtual ICollection<EventoTipo> EventoTipoIdUsuarioCreacionNavigation { get; set; } = new List<EventoTipo>();

    public virtual ICollection<EventoTipo> EventoTipoIdUsuarioUltimaModificacionNavigation { get; set; } = new List<EventoTipo>();

    public virtual ICollection<Grupo> GrupoIdUsuarioCreacionNavigation { get; set; } = new List<Grupo>();

    public virtual ICollection<Grupo> GrupoIdUsuarioUltimaModificacionNavigation { get; set; } = new List<Grupo>();

    public virtual ICollection<GrupoPunto> GrupoPunto { get; set; } = new List<GrupoPunto>();

    public virtual Usuario IdUsuarioCreacionNavigation { get; set; }

    public virtual UsuarioGrupo IdUsuarioGrupoNavigation { get; set; }

    public virtual Usuario IdUsuarioUltimaModificacionNavigation { get; set; }

    public virtual ICollection<Usuario> InverseIdUsuarioCreacionNavigation { get; set; } = new List<Usuario>();

    public virtual ICollection<Usuario> InverseIdUsuarioUltimaModificacionNavigation { get; set; } = new List<Usuario>();

    public virtual ICollection<PuntoDato> PuntoDatoIdUsuarioCreacionNavigation { get; set; } = new List<PuntoDato>();

    public virtual ICollection<PuntoDato> PuntoDatoIdUsuarioUltimaModificacionNavigation { get; set; } = new List<PuntoDato>();

    public virtual ICollection<PuntoEvento> PuntoEventoIdUsuarioCreacionNavigation { get; set; } = new List<PuntoEvento>();

    public virtual ICollection<PuntoEvento> PuntoEventoIdUsuarioUltimaModificacionNavigation { get; set; } = new List<PuntoEvento>();

    public virtual ICollection<Punto> PuntoIdUsuarioCreacionNavigation { get; set; } = new List<Punto>();

    public virtual ICollection<Punto> PuntoIdUsuarioUltimaModificacionNavigation { get; set; } = new List<Punto>();

    public virtual ICollection<UsuarioGrupo> UsuarioGrupoIdUsuarioCreacionNavigation { get; set; } = new List<UsuarioGrupo>();

    public virtual ICollection<UsuarioGrupo> UsuarioGrupoIdUsuarioUltimaModificacionNavigation { get; set; } = new List<UsuarioGrupo>();

    public virtual ICollection<UsuarioGrupoPermiso> UsuarioGrupoPermiso { get; set; } = new List<UsuarioGrupoPermiso>();

    public virtual ICollection<UsuarioParametro> UsuarioParametro { get; set; } = new List<UsuarioParametro>();
}